name: Clang Build & Test

on:
  push:
    branches:
      - main
      - "v*.*"
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  ci_test_clang:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler:
          [
            "5",
            "6",
            "7",
            "8",
            "9",
            "10",
            "11",
            "12",
            "13",
            "14",
            "15",
            "16",
            "latest",
          ]
    container: silkeh/clang:${{ matrix.compiler }}
    steps:
      - name: Install git and unzip
        run: apt-get update ; apt-get install -y git unzip
      - uses: actions/checkout@v3
      - name: Get latest CMake and ninja
        uses: lukka/get-cmake@v3.27.7
      - name: Run CMake
        run: cmake -S . -B build -DACTIVECPP_BuildExamples=On
      - name: Build
        run: cmake --build build
      - name: Run tests
        run: ctest --test-dir build
