name: GCC Build & Test

on:
  push:
    branches:
      - main
      - "v*.*"
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  ci_test_gcc:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: ["8", "9", "10", "11", "12", "13", "latest"]
    container: gcc:${{ matrix.compiler }}
    steps:
      - uses: actions/checkout@v3
      - name: Get latest CMake and ninja
        uses: lukka/get-cmake@v3.27.7
      - name: Run CMake
        run: cmake -S . -B build -DACTIVECPP_BuildExamples=On
      - name: Build
        run: cmake --build build
      - name: Run tests
        run: ctest --test-dir build
